services:
  postgres:
    image: postgres:18
    container_name: battletanks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: battletanks
      POSTGRES_PASSWORD: battletanks
      POSTGRES_DB: battletanks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: battletanks-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@battletanks.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:8
    container_name: battletanks-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  emqx:
    image: emqx/emqx:5.8
    container_name: battletanks-emqx
    restart: unless-stopped
    environment:
      EMQX_NAME: battletanks-broker
      EMQX_HOST: node1.emqx.local
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: public
    ports:
      - "1883:1883"      # MQTT TCP
      - "8083:8083"      # MQTT WebSocket
      - "18083:18083"    # Dashboard HTTP
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  emqx_data:
  emqx_log: